### ISSUE TITLE
Multiple Sample xcmsSet error (getAllPeakEICs)

### ISSUE THREAD

**Issue by hhabra** [osenan/cliqueMS#2]
Hi there Oriol,

I'm checking out this package for the first time. Before I inquire about this error, I wanted to ask if this package can handle an xcmsSet with multiple samples (or a multiple sample XCMSnExp for that matter)? The manuscript for cliqueMS contained some multiple-sample annotation comparisons, hence my question.

If the answer is no, then I suppose that answers my question. 
If yes, I was trying an xcmsSet object with multiple samples and ran into the error:

> Error in CAMERA::getAllPeakEICs(xsan, rep(1, nrow(peaklist))) : 
>   Index length must equals number of peaks.
> 

Is there any specific way you recommend doing multiple-sample annotation with cliqueMS?

**Comment by hhabra** [comment]
Never mind, found the answer to my question. Good luck!

**Comment by AJCharles** [comment]
Just had the same issue, would it be possible to share your findings? 

I also had come to the conclusion from reading the manuscript that it could handle multigroup annotation. However, I don't see whether this issue needs to be addressed in a different manner, or that it simply cannot be done with a multi-group object

Best, 
A

**Comment by osenan** [comment]
Dear @hhabra and @AJCharles ,

Currently, `cliqueMS` cannot handle aligned samples, nor in a `xcmsSet` or a `XCMSnExp`. `cliqueMS` analyzes samples one by one. This is also interesting because when you analyze samples one by one, you can annotate some metabolites that if you would be using the aligned feature matrix would not be annotated. The reason is that some individual samples may contain some adducts which are not shared by most of the samples, and often these features are not included in the aligned matrix. So, depending on the type of metabolomic analysis that you need analysing samples one by one is particularly interesting.
On the other hand, we are developing `cliqueMS` to work with aligned samples. This feature will be included in new versions.
