### ISSUE TITLE
Cannot install through devtools or CRAN

### ISSUE THREAD

**Issue by gwilson9** [osenan/cliqueMS#3]
The project does not exist on CRAN.

Also tried devtools and get the following error:

Downloading GitHub repo osenan/cliqueMS@master
C:\TPP\bin\tar.exe: Cannot use compressed or remote archives
C:\TPP\bin\tar.exe: Error is not recoverable: exiting now
External tar failed with `--force-local`, trying without
C:\TPP\bin\tar.exe: Cannot use compressed or remote archives
C:\TPP\bin\tar.exe: Error is not recoverable: exiting now
External tar failed with `--force-local`, trying without
Error: Failed to install 'cliqueMS' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)

**Comment by osenan** [comment]
Dear @gwilson9,

The package has been archived from CRAN because one of its dependencies, package mzR, was removed from CRAN. Currently I am uploading the package to Bioconductor, so hopefully soon will be again avaiable from a R repository.
In regard to what you comment, it seems that some problem happened while decompressing the package after `install_github("osenan/cliqueMS")` command. I'll suggest you to try again, and test if this command works for you in other packages. Moreover, you can download yourself the package from the github repository (use the download or clone button and download as a zip), decompress the file, open a Terminal, and try to build & install yourself the package with
`R CMD build` and `R CMD INSTALL`.
